# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac230836625cc60d9a2666273962a0583d92f15a397b802f3b31e2b1bc1fc2c1d25cb041f205c0fd5751862d83e22fac86d1b74ce71f0deb746b1e5e755c3eb4

test:
  secret_key_base: 4bcfe4b8707f0b8e63bfd9b79535a727f74f57bbbadf4c737756b9a429fbb2f58f40acb3c8062ab7d90db932c2594cbc8aa4dba04b9bb8f717ba3279bd354cae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
